spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8

server:
  port: 11510

logging:
  config: classpath:logback-spring.xml

logback:
  path: E:/devData/logs/litemall-all
